###USER APIS


###For user registration
POST http://localhost:4000/user-api/register
Content-Type: application/json

{
  "email":"testgdo@westagilelabs.com",
  "username":"test gdo",
  "password":"testgdo"
}

###For user login
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
  "email":"yamini@westagilelabs.com",
  "password":"yamini"
}

###forget password
POST http://localhost:4000/user-api/forget-password
Content-Type: application/json

{
  "email":"saideepthi.p@westagilelabs.com"
}

###reset password
PUT  http://localhost:4000/user-api/reset-password/email/saideepthi.p@westagilelabs.com
Content-Type: application/json

{
    "otp":266101,
    "password":"Deepthi@134"
}



###SUPER ADMIN APIS


###get users data
GET http://localhost:4000/super-admin-api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3VwZXIgYWRtaW4iLCJlbWFpbCI6InNhcmF0aEB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY3ODc4NDE1OCwiZXhwIjoxNjc4ODAyMTU4fQ.sjpBveWO-q-lyg0ED6J46h39NzXsK8DDbiyv2iMU0-I

###super admin maps the role for existing user
PUT http://localhost:4000/super-admin-api/user/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3VwZXIgYWRtaW4iLCJpYXQiOjE2Nzg3NjkyNDMsImV4cCI6MTY3ODc4NzI0M30.lLpH3hCKOOai1Kou-IWH0qPyx10mllRCLmHAwKI0TwM

{
  "email":"testgdo@westagilelabs.com",
  "role":"GDO head"
}



###ADMIN-APIS


###admin creates a project
POST http://localhost:4000/admin-api/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6InNhc2hpLmR1bW15QHdlc3RhZ2lsZWxhYnMuY29tIiwiaWF0IjoxNjc4Nzg1NjU0LCJleHAiOjE2Nzg4MDM2NTR9.GeoPlFU50nBHo_A6c4NTZCAY4wf1_mgTJMfJKATOxkc

{
"projectName":"test project",
"client":"vishnu",
"clientAccountManager":"pavan",
"statusOfProject":"In progress",
"startDate" :"2023/02/19",
"overallProjectFitnessIndicator":"green",
"domain":"testing",
"typeOfProject":"manual testing",
"teamSize":3,
"gdoHeadEmail":"testgdo@westagilelabs.com",
"projectManagerEmail":"teju@westagilelabs.com"
}

###get all project details
GET http://localhost:4000/admin-api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6InNhc2hpLmR1bW15QHdlc3RhZ2lsZWxhYnMuY29tIiwiaWF0IjoxNjc4Nzg4MTQxLCJleHAiOjE2Nzg4MDYxNDF9.TqoBozRhYPS0wFO8OvOmWXIwuzjwF5ENDEqfQOcB4F4

###get specific project details
GET http://localhost:4000/admin-api/projectId/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6InNhc2hpLmR1bW15QHdlc3RhZ2lsZWxhYnMuY29tIiwiaWF0IjoxNjc4Nzg3NjIwLCJleHAiOjE2Nzg4MDU2MjB9.5oM3GMgfsUBMxEVBCjGiH5jH1u79Y864Zf1gDgux2IY

###get all resource requests
GET http://localhost:4000/admin-api/resource-requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6InNhc2hpLmR1bW15QHdlc3RhZ2lsZWxhYnMuY29tIiwiaWF0IjoxNjc4Nzg3NjIwLCJleHAiOjE2Nzg4MDU2MjB9.5oM3GMgfsUBMxEVBCjGiH5jH1u79Y864Zf1gDgux2IY

###update project details
PUT http://localhost:4000/admin-api/projectId/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2Nzg3Njk0ODEsImV4cCI6MTY3ODc4NzQ4MX0.YUO8JH79mrEO5744kBm_6rU6fE_cYZmJhoNDyGC_uaE

{
"projectId" :1,
"projectName":"project 1",
"client":"vamsi",
"clientAccountManager":"Bhanu",
"statusOfProject":"In progress",
"startDate" :"2023/02/09",
"overallProjectFitnessIndicator":"amber",
"domain":"cloud computing",
"typeOfProject":"Devops",
"teamSize":3,
"gdoHeadEmail":"ravi@westagilelabs.com",
"projectManagerEmail":"srikar@westagilelabs.com"
}

###delete a project
DELETE  http://localhost:4000/admin-api/projectId/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiR0RPIGhlYWQiLCJlbWFpbCI6InJhdmlAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg4MDkwMDAsImV4cCI6MTY3ODgyNzAwMH0.x_RLUE13-6OTFqWmxP-Udcf2oxfVlhonZDiFncoKIWM


###GDO-HEAD-APIS


###GDO-head adds existing employees to projects
POST http://localhost:4000/gdoHead-api/team
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiR0RPIGhlYWQiLCJlbWFpbCI6InlhbWluaUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY3ODgxMjQyNCwiZXhwIjoxNjc4ODMwNDI0fQ.jkmwDtHfeZI0w9nRSobaWXtps74sfrf3E98zSXXwR5U

{
"projectId":2,
"empId":25,
"empName":"janu",
"role":"Dev",
"startDate":"2023/02/19",
"status":"Active",
"billingStatus":"billed",
"exposedToCustomer":true,
"allocationType":"permanent"
}

###update team details
PUT http://localhost:4000/gdoHead-api/update-team
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiR0RPIGhlYWQiLCJlbWFpbCI6InlhbWluaUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY3ODgxMjQyNCwiZXhwIjoxNjc4ODMwNDI0fQ.jkmwDtHfeZI0w9nRSobaWXtps74sfrf3E98zSXXwR5U

{
"projectId":2,
"empId":4,
"empName":"Bhavana",
"role":"Devops",
"startDate":"2023/01/19",
"status":"Active",
"billingStatus":"billed",
"exposedToCustomer":true,
"allocationType":"permanent"
}

###delete team details
DELETE http://localhost:4000/gdoHead-api/delete-team-member/projectId/2/empId/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiR0RPIGhlYWQiLCJlbWFpbCI6InlhbWluaUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY3ODgxMjQyNCwiZXhwIjoxNjc4ODMwNDI0fQ.jkmwDtHfeZI0w9nRSobaWXtps74sfrf3E98zSXXwR5U

###GDO-head raises a resource request
POST http://localhost:4000/gdoHead-api/projectId/2/resourcing-request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiR0RPIGhlYWQiLCJlbWFpbCI6InlhbWluaUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY3ODgxMjQyNCwiZXhwIjoxNjc4ODMwNDI0fQ.jkmwDtHfeZI0w9nRSobaWXtps74sfrf3E98zSXXwR5U

{
  "requestDesc":"Need one more resource",
  "GdoEmail" :"ravi@westagilelabs.com",
  "projectId":2
}

###get project details under him
GET http://localhost:4000/gdoHead-api/projects/testgdo@westagilelabs.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiR0RPIGhlYWQiLCJlbWFpbCI6InRlc3RnZG9Ad2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg3ODYyOTIsImV4cCI6MTY3ODgwNDI5Mn0.IrnMC22xHr0VD7NpGManQPVHBRoHRhLeVYdMNHGWIs4

###get specific project details
GET http://localhost:4000/gdoHead-api/projectId/9/gdoEmail/testgdo@westagilelabs.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiR0RPIGhlYWQiLCJpYXQiOjE2Nzg3Njk2MDUsImV4cCI6MTY3ODc4NzYwNX0.byFyIKL-zhWh5ZQU6WhEsagVe8901JWDbB0KFXRz5bI



###PROJECT MANAGER APIS


###project manager updates project details
POST http://localhost:4000/project-manager-api/projectId/4/project-update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicHJvamVjdCBtYW5hZ2VyIiwiZW1haWwiOiJzcmlrYXJAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg4MTE1NTYsImV4cCI6MTY3ODgyOTU1Nn0.qUnLqce1scRZOfYmIutSmMYjM_7HbpEFVQJ7A6xQOE8

{
  "projectId":4,
  "projectManager":"chandu@westagilelabs.com",
  "date":"2023/01/28",
  "statusUpdate":"New feature updated",
  "scheduleStatus":"Red",
  "resourcingStatus":"Green",
  "qualityStatus":"Green",
  "clientInputs":false
}

###project manager raises project concerns
POST http://localhost:4000/project-manager-api/projectId/4/raise-project-concern
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicHJvamVjdCBtYW5hZ2VyIiwiZW1haWwiOiJzcmlrYXJAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg4MTE1NTYsImV4cCI6MTY3ODgyOTU1Nn0.qUnLqce1scRZOfYmIutSmMYjM_7HbpEFVQJ7A6xQOE8

{
  "projectId":4,
  "concernDescription":"More systems required",
  "raisedBy":"chandu@westagilelabs.com",
  "raisedOnDate":"2023/02/24",
  "severity":"Critical",
  "concernRaisedInternallyOrNot":true,
  "status":"mitigated",
  "mitigatedOn":"2023/03/06"
}

###get project manager projects
GET http://localhost:4000/project-manager-api/project/srikar@westagilelabs.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicHJvamVjdCBtYW5hZ2VyIiwiZW1haWwiOiJzcmlrYXJAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg3OTIwNTYsImV4cCI6MTY3ODgxMDA1Nn0.c9xa0z9mjcA5MBO-xyNiXfmkOfWyMYxTOJFUsVr6xpk

###Update project updates
PUT http://localhost:4000/project-manager-api/update/project-updates/projectId/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicHJvamVjdCBtYW5hZ2VyIiwiZW1haWwiOiJzcmlrYXJAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg4MTE1NTYsImV4cCI6MTY3ODgyOTU1Nn0.qUnLqce1scRZOfYmIutSmMYjM_7HbpEFVQJ7A6xQOE8

{
  "projectId":4,
  "projectManager":"chandu@westagilelabs.com",
  "date":"2023/01/28",
  "statusUpdate":"New feature updated",
  "scheduleStatus":"Green",
  "resourcingStatus":"Green",
  "qualityStatus":"Green",
  "clientInputs":false
}

###delete project updates
DELETE http://localhost:4000/project-manager-api/projectId/4/date/2023-02-27 00:00:00
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicHJvamVjdCBtYW5hZ2VyIiwiZW1haWwiOiJzcmlrYXJAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg4MTE1NTYsImV4cCI6MTY3ODgyOTU1Nn0.qUnLqce1scRZOfYmIutSmMYjM_7HbpEFVQJ7A6xQOE8

###update project concerns
PUT http://localhost:4000/project-manager-api/update-concern/projectId/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicHJvamVjdCBtYW5hZ2VyIiwiZW1haWwiOiJzcmlrYXJAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg4MTE1NTYsImV4cCI6MTY3ODgyOTU1Nn0.qUnLqce1scRZOfYmIutSmMYjM_7HbpEFVQJ7A6xQOE8

{
  "projectId":4,
  "concernDescription":"More systems required",
  "raisedBy":"chandu@westagilelabs.com",
  "raisedOnDate":"2023/03/04",
  "severity":"Critical",
  "concernRaisedInternallyOrNot":true,
  "status":"mitigated",
  "mitigatedOn":"2023/03/06"
}

###delete project concerns
DELETE http://localhost:4000/project-manager-api/project-concern/projectId/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicHJvamVjdCBtYW5hZ2VyIiwiZW1haWwiOiJzcmlrYXJAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg4MTE1NTYsImV4cCI6MTY3ODgyOTU1Nn0.qUnLqce1scRZOfYmIutSmMYjM_7HbpEFVQJ7A6xQOE8